name: Uses Examples

on:
  workflow_dispatch:

jobs:
  uses_example:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Install Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Toon huidige directory en bestanden
        run: |
          pwd
          ls -lha

      - name: Run my_script.py
        run: python my_script.py
